api:
  elevenlabs:
    key: "your-elevenlabs-api-key-here"
    url: "https://api.elevenlabs.io/v1/text-to-speech/JBFqnCBsd6RMkjVDRZzb?output_format=mp3_44100_128"
    test_payload: |
      {
        "text": "The first move is what sets everything in motion.",
        "model_id": "eleven_multilingual_v2"
      }

mongodb:
  enabled: true
  dsn: "mongodb://localhost:27017"
  database: "regproxy"
  collection: "proxy"
  timeout: 10  # connection timeout in seconds

daemon:
  interval: 300  # seconds between proxy checks
  threads: 20    # number of concurrent threads for testing
  timeout: 10    # timeout in seconds for requests
  log_level: "info"

proxy:
  sources_refresh_interval: 3600  # seconds between crawling new proxies
  max_crawl_workers: 15
  test_sample_size: 100  # number of proxies to test each cycle
  keep_working_proxies: 50  # maximum number of working proxies to keep

files:
  working_proxies: "working_proxies.txt"
  all_proxies: "proxies.txt"
  log_file: "daemon.log"
